### PR TITLE
Refactor eyesswitchto

### PR DESCRIPTION
**Pull request by Infernion**

### CODE REVIEW

**Comment by Dude-X** [comment]
Does this branch fix issues with working with iframes?

**Comment by Infernion** [comment]
@Dude-X which issue do you mean?

**Comment by Dude-X** [comment]
@Infernion It's not a bug per se, but given a locator (By, String) it will retrieve it only once and then use that element multiple times. We get `StaleElementReferenceExceptions` occasionally due to some minor modification of the DOM.

**Comment by Infernion** [comment]
@Dude-X this issue related to switching between frames. This will be fixed but in the following PR.

**Pull request merged**
